# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Checkins::Checkout::CreateStripeInvoice; end
module Checkins::Checkout::SaveCheckout; end
module Jellyswitch::Events::Jellyswitch::Events::Channel::ActiveSupportNotification; end
module Jellyswitch::Events::Jellyswitch::Events::Channel::Sidekiq; end
module Jellyswitch::Events::Jellyswitch::Events::Registry; end
